### PR TITLE
Piggyback on cleveref's "line" definition

### PR DESCRIPTION
**Pull request by real-or-random**
This provides all the necessary definitions and also has the advantage that it respects cleveref's capitalization options.

### CODE REVIEW

**Comment by arnomi** [comment]
Looks super clean, thanks. I'll try to take a closer look at it over the next days/weeks.

**Comment by real-or-random** [comment]
By the way, I think this is safe to do whenever cleveref is loaded, so maybe a separate `\pcfixcleveref` command is actually not necessary. But I don't know the story behind `\pcfixhyperref`...

**Comment by real-or-random** [comment]
Could you have a look?

**Review by arnomi — APPROVED** [review]
Looks good as far as I can tell. Thanks.

**Pull request merged**
